added some more bash script

diff --git a/s3/bash_script/put-object b/s3/bash_script/put-object
--- a/s3/bash_script/put-object
+++ b/s3/bash_script/put-object
@@ -1,21 +1,42 @@
-#!/usr/bin/env bash 
+#!/usr/bin/env bash
 
-# where we will store these files 
-OUTPUT_DIR="./tmp/files"
+echo "putting object in bucket - $1"
 
-rm -r $OUTPUT_DIR
+# check bucket
+if [ -z "$1" ]; then
+  echo "provide bucket name"
+  exit 1
+fi
 
-mkdir -p $OUTPUT_DIR
+# check file
+if [ -z "$2" ]; then
+  echo "provide file path"
+  exit 1
+fi
 
-for((i=1; i<=10; i++));
-do 
-  touch "$OUTPUT_DIR/file_$i.txt"
-  echo "file_$i.txt" > "$OUTPUT_DIR/file_$i.txt"
-done
+# check content-type
+if [ -z "$3" ]; then
+  echo "provide content-type"
+  exit 1
+fi
 
+BUCKET_NAME=$1
+FILE_NAME=$2
+CONTENT_TYPE=$3
 
+# object key = file name only
+OBJECT_KEY=$(basename "$FILE_NAME")
 
+# verify file exists
+if [ ! -f "$FILE_NAME" ]; then
+  echo "error: file not found -> $FILE_NAME"
+  exit 1
+fi
 
+echo "> aws s3api put-object --bucket $BUCKET_NAME --key $OBJECT_KEY --content-type $CONTENT_TYPE --body $FILE_NAME"
 
-
-
+aws s3api put-object \
+  --bucket "$BUCKET_NAME" \
+  --key "$OBJECT_KEY" \
+  --content-type "$CONTENT_TYPE" \
+  --body "$FILE_NAME"
